# Power method

In [1]:
import numpy as np

In [2]:
A = np.array([
    [2.0, 1.0, 5.0],
    [5.0, 7.0, 9.0],
    [4.0, 6.0, 1.0],
])
print('A= ')
print(A)

A= 
[[2. 1. 5.]
 [5. 7. 9.]
 [4. 6. 1.]]


In [3]:
w, v = np.linalg.eig(A)
print('eigenvalues = ', w)

eigenvalues =  [13.78378635  0.83287417 -4.61666053]


## Power method to find the largest (in absolute value) eigenvalue

### Algorithm 0 - test

In [7]:
# initial guess
u = np.random.random((3,1))
# itmax: max. iteration number
itmx = 10
# initial iteration
k=0
while (k<itmx):
  v = A.dot(u)
  lamb = np.linalg.norm(v)
  u = v/lamb
  k = k+1
  print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  1    lamb=  12.800967650556085     error =  0.9828187014223548
k=  2    lamb=  13.259013874695652     error =  0.524772477282788
k=  3    lamb=  13.869394591535832     error =  0.08560823955739139
k=  4    lamb=  13.743537513410716     error =  0.040248838567723766
k=  5    lamb=  13.795880902269896     error =  0.01209455029145623
k=  6    lamb=  13.779573484432081     error =  0.004212867546359078
k=  7    lamb=  13.785178900260135     error =  0.001392548281694772
k=  8    lamb=  13.783317844026826     error =  0.00046850795161468284
k=  9    lamb=  13.783943034943864     error =  0.00015668296542337146
k=  10    lamb=  13.783733846914052     error =  5.2505064388697065e-05


### Algorithm 1

$$
\lambda^{(k+1)} = \|x^{(k+1)}\| \to |\lambda_1|
$$

In [9]:
# initial guess
u = np.random.random((3,1))
u = u/np.linalg.norm(u)
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
lamb0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = A.dot(u)
  lamb1 = np.linalg.norm(v)
  u = v/lamb1
  rel_diff = abs((lamb1-lamb0)/lamb0)
  k = k+1
  lamb0 = lamb1

print('k= ', k, '   lamb= ', lamb1, '    error = ', abs(lamb1-w[0]))

k=  20    lamb=  13.783786351842322     error =  1.361186718895624e-10


### Algorithm 2

$$
\lambda^{(k+1)} = \ell(x^{(k+1)}) \to \lambda_1
$$

In [13]:
# initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
lamb0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = A.dot(u)
  lamb1 = v[1,0]
  u = v/lamb1
  rel_diff = abs((lamb1-lamb0)/lamb0)
  k = k+1
  lamb0 = lamb1

print('k= ', k, '   lamb= ', lamb1, '    error = ', abs(lamb1-w[0]))

k=  22    lamb=  13.7837863518019     error =  1.765396717701151e-10


## Inverse power method to find the smallest (in absolute value) eigenvalue

### Algorithm 2

$$
\mu^{(k+1)} = \ell(x^{(k+1)}) \to \frac{1}{\lambda_1}
$$

In [16]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = np.linalg.solve(A, u)
  mu1 = v[1,0]
  u = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1

# eigenvalue = 1/mu
lamb = 1.0/mu1
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[1]))

k=  16    lamb=  0.8328741741112113     error =  3.967826067707847e-12


## Shift-inverse power method to find the eigenvalue that is closest to a given one

### Algorithm 2

$$
\mu^{(k+1)} = \ell(x^{(k+1)}) \to \frac{1}{\lambda_1-\sigma}
$$

In [20]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
# As: shifted matrix
# As = A - sigma*I
As = A - sigma*np.identity(3)
while ( (k<itmx) and (rel_diff>Tol) ):
  v = np.linalg.solve(As, u)
  mu1 = v[1,0]
  u = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1

# eigenvalue = sigma+1/mu
lamb = sigma+1.0/mu1
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  28    lamb=  13.783786352063938     error =  8.549783103717346e-11


## Inverse power method with variant shift to find one of the eigenvalue

### Algorithm 2

In [50]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  sigma0 = sigma
  # As: shifted matrix
  # As = A - sigma*I
  As = A - sigma*np.identity(3)
  v = np.linalg.solve(As, u)
  mu1 = v[1,0]
  u = v/mu1
  sigma = sigma + 1.0/mu1
  rel_diff = abs((sigma0-sigma)/sigma0)
  k = k+1

# eigenvalue = sigma
lamb = sigma
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  5    lamb=  13.78378635197845     error =  8.881784197001252e-15


### Algorithm 3: With Rayleigh quotient

In [51]:
# Initial guess
u = np.random.random((3,1))
u = u/np.linalg.norm(u)
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  sigma0 = sigma
  # As: shifted matrix
  # As = A - sigma*I
  As = A - sigma*np.identity(3)
  v = np.linalg.solve(As, u)
  mu1 = np.linalg.norm(v)
  u = v/mu1
  sigma = (u.T).dot(A.dot(u))
  rel_diff = abs((sigma0-sigma)/sigma0)
  k = k+1

# eigenvalue = sigma
lamb = sigma
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  5    lamb=  [[13.78378635]]     error =  [[7.10542736e-15]]
