## Power method

As a first example, given a 3-by-3 matrix A

In [1]:
A = [2 1 5; 5 7 9; 4 6 1]

3×3 Array{Int64,2}:
 2  1  5
 5  7  9
 4  6  1

All of it's eigenvalues can be evaluated by the comment "eigvals"

In [2]:
using LinearAlgebra
e_A = eigvals(A); 
println(e_A[1]) 
println(e_A[2]) 
println(e_A[3])

13.78378635197844
0.8328741741072435
-4.616660526085692


# Basic Power method
Given a random vector u, we compute A*u several times, here, 10 times.

In [6]:
u = rand(3);
for ii=1:10
    global mu
    global u
    v = A*u;
    mu = norm(v,2);
    u = v/mu;
end
println("After 10 iterations, \n")
println("the largest eigenvalue is approximately ", mu)

After 10 iterations, 

the largest eigenvalue is approximately 13.783763471950946


The second attempt, we define an epsilon to test if the process converges or not.

In [5]:
u = rand(3);
mu0 = 0;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(mu-mu0)>eps
    mu0 = mu;
    v = A*u;
    mu = v[2];
    u = v/mu;
    ii=ii+1;
end
println("Largest eigenvalue is ", mu)
println("# of iterations= ", ii)

Largest eigenvalue is 13.78378635199191
# of iterations= 25


## Inverse power method
To find the smallest eigenvalue we compute $A^{-1}u$ several times until the process converges.

In [6]:
u = rand(3); u=u/norm(u,2);
mu0 = 0;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(mu-mu0)>eps
    mu0 = mu;
    v = A\u;
    mu = v[2];
    u = v/mu;
    ii=ii+1;
end
println("Smallest eigenvalue is ", 1/mu)
println("# of iterations= ", ii)

Smallest eigenvalue is 0.8328741741143922
# of iterations= 15


## Shift-inverse power method
To find the eigenvalue that is closest to $\sigma$ we compute $(A-\sigma I)^{-1}u$ several times until the process converges.

In [7]:
u = rand(3); u=u/norm(u,2);
sigma = -10;
mu0 = 0;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(mu-mu0)>eps
    mu0 = mu;
    v = (A-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    ii = ii+1;
end
println("The eigenvalue that is closest to ", sigma, " is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue that is closest to -10 is -4.616660524001687
# of iterations= 34


## Shift-inverse power method - Algorithm 2
To find the eigenvalue that is closest to $\sigma$ we compute $(A-\sigma I)^{-1}u$ several times until the process converges.

In [8]:
u = rand(3); u=u/norm(u,2);
sigma = 0;
sigma0 = 1;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (A-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    sigma = sigma+ 1/mu;
    ii = ii+1;
end
println("The eigenvalue is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue is 0.8328741741072434
# of iterations= 7


## Shift-inverse power method - Algorithm 3
To find the eigenvalue that is closest to $\sigma$ we compute $(A-\sigma I)^{-1}u$ several times until the process converges.

In [9]:
u = rand(3); u=u/norm(u,2);
sigma = u'*A*u;
sigma0 = 1;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (A-sigma*UniformScaling(1))\u;
    v = v/norm(v,2);
    sigma = v'*A*v;
    ii = ii+1;
end
println("The eigenvalue is ", sigma)
println("# of iterations= ", ii)

The eigenvalue is 13.783786351977671
# of iterations= 11


Let's try a bigger symmetric matrix, with size $n=10$

In [10]:
n = 10;
B = rand(n,n) .- 0.5; B = B+B';
e_B = eigvals(B);
for ii=1:n
    println(e_B[ii]) 
end

-2.604406597766613
-1.470962453105976
-0.8222941411012477
-0.4369893570250568
0.22330174731798777
0.2488829649192796
0.9828412435203444
1.2743120919546858
1.73955154933266
1.920023759840795


Shift-inverse power method - Algorithm 1

In [11]:
u = rand(n); u=u/norm(u,2);
sigma = -1;
mu0 = 0; mu = 1;
eps = 1.0e-10; ii=0;
while abs.(mu-mu0)>eps
    mu0 = mu;
    v = (B-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    ii = ii+1;
end
println("The eigenvalue is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue is -0.8222941411006368
# of iterations= 29


Shift-inverse power method - Algorithm 2

In [12]:
u = rand(n); u=u/norm(u,2);
sigma = -1; sigma0 = 1;
mu = 1;
eps = 1.0e-10; ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (B-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    sigma = sigma + 1/mu;
    ii = ii+1;
end
println("The eigenvalue is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue is -0.4369893570254946
# of iterations= 10


Shift-inverse power method - Algorithm 3

In [13]:
u = rand(n); u=u/norm(u,2);
sigma = -1; sigma0 = 1;
mu = 1;
eps = 1.0e-10; ii=0;
while abs.(sigma-sigma0)>eps
    global v
    sigma0 = sigma;
    v = (B-sigma*UniformScaling(1))\u;
    v = v/norm(v,2);
    sigma = v'*B*v;
    ii = ii+1;
end
println("The eigenvalue is ", sigma)
println("# of iterations= ", ii)

The eigenvalue is -0.8222941411012478
# of iterations= 5


In [15]:
lambda_1 = sigma;
v1 = v;

## Deflation (For symmetric matrix)
Given a symmetric metrix $A$, suppose we found the eigenvalue $\lambda_1$ and eigenvector $v_1$,
we can define a new matrix $B = A - \lambda_1 vv^T$

In [16]:
B2 = B - lambda_1*v1*v1';
e_B2 = eigvals(B2); e_B2 = sort(e_B2);
for ii=1:n
    println(e_B[ii], "    ", e_B2[ii])
end

-2.604406597766613    -2.604406597766616
-1.470962453105976    -1.470962453105976
-0.8222941411012477    -0.436989357025056
-0.4369893570250568    1.2851053790877384e-16
0.22330174731798777    0.22330174731798702
0.2488829649192796    0.24888296491927955
0.9828412435203444    0.9828412435203433
1.2743120919546858    1.274312091954682
1.73955154933266    1.7395515493326585
1.920023759840795    1.920023759840793


In [17]:
x = zeros(n); 
x[1] = 1/v1[1];
B3 = B - lambda_1*v1*x';
e_B3 = eigvals(B3); e_B3 = sort(e_B3);
for ii=1:n
    println(e_B[ii], "    ", e_B3[ii])
end

-2.604406597766613    -2.60440659776662
-1.470962453105976    -1.4709624531059748
-0.8222941411012477    -0.43698935702505726
-0.4369893570250568    8.710641312251513e-16
0.22330174731798777    0.22330174731798969
0.2488829649192796    0.2488829649192773
0.9828412435203444    0.982841243520341
1.2743120919546858    1.2743120919546826
1.73955154933266    1.739551549332659
1.920023759840795    1.920023759840797


Wielandt Deflation

In [18]:
x = B[1,:]/(lambda_1*v1[1]);
B4 = B - lambda_1*v1*x';
e_B4 = eigvals(B4); e_B4 = sort(e_B4);
for ii=1:n
    println(e_B[ii], "    ", e_B4[ii])
end

-2.604406597766613    -2.604406597766616
-1.470962453105976    -1.4709624531059775
-0.8222941411012477    -0.43698935702505665
-0.4369893570250568    0.0
0.22330174731798777    0.22330174731798738
0.2488829649192796    0.24888296491927683
0.9828412435203444    0.9828412435203433
1.2743120919546858    1.2743120919546844
1.73955154933266    1.739551549332658
1.920023759840795    1.920023759840795


Wielandt Deflation

A small test showing that the size of the matrix can be reduced by one

In [20]:
n = 4;
C = rand(n,n) .- 0.5; C = C+C';
e_C = eigvals(C);

u = rand(n); u=u/norm(u,2);
sigma = 0; sigma0 = 1;
mu = 1;
eps = 1.0e-10; ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (C-sigma*UniformScaling(1))\u;
    v = v/norm(v,2);
    sigma = v'*C*v;
    ii = ii+1;
end
lambda_1 = sigma; v1 = v;

x = C[1,:]/(lambda_1*v1[1]);
C2 = C - lambda_1*v1*x';
e_C2 = eigvals(C2); e_C2 = sort(e_C2);

C3 = C2[2:n, 2:n];
e_C3 = eigvals(C3); e_C3 = sort(e_C3);
println(e_C)
println(e_C2)
println(e_C3)

[-1.1732, 0.269916, 0.535634, 1.12684]
[-1.1732, 0.0, 0.535634, 1.12684]
[-1.1732, 0.535634, 1.12684]


## Subspace iteration

In [21]:
n=1000;
A = rand(n, n).-0.5;
A = A+A';

Try to find $4$ largest (absolute) eigenvalues

In [22]:
# Constructing a set of orthonormal vectors
u2 = zeros(n,4);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;
w = rand(n,1); w = w/norm(u,2);
w = w - (w'*u).*u; w = w - (w'*v).*v;
u2[:,3] = w;
x = rand(n,1); x = x/norm(u,2);
x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
u2[:,4] = x;

# Initialize the eigenvalue
mu = ones(1,4); mu2 = zeros(1,4);

# Define epsilon
eps = 1.0e-10; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = A*u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    w = v2[:,3]; mu[1,3] = norm(w,2); w = w/mu[1,3];
    x = v2[:,4]; mu[1,4] = norm(x,2); x = x/mu[1,4];
    v = v - (v'*u).*u;
    w = w - (w'*u).*u; w = w - (w'*v).*v;
    x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
    u2[:,1] = u; u2[:,2] = v; u2[:,3] = w; u2[:,4] = x;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", mu[1,1])
println("The 2nd eigenvalue is  ", mu[1,2])
println("The 3rd eigenvalue is  ", mu[1,3])
println("The 4th eigenvalue is  ", mu[1,4])
println("# of iterations= ", ii)

The 1st eigenvalue is  26.01857313404932
The 2nd eigenvalue is  25.644570687246436
The 3rd eigenvalue is  25.458012116630716
The 4th eigenvalue is  25.115738363725832
# of iterations= 4347


In [23]:
eigvals(A)

1000-element Array{Float64,1}:
 -25.644570687246368
 -25.09643056892713 
 -24.9735688903644  
 -24.85072059475573 
 -24.847784907302835
 -24.606717752138284
 -24.43010373444591 
 -24.275627068884475
 -24.235462514262355
 -24.080698930075716
 -23.979042924287295
 -23.904742083231145
 -23.825387085925037
   ⋮                
  23.944673986296422
  23.95949995637701 
  24.136531290175235
  24.168050970289773
  24.446289468520806
  24.713674978581963
  24.753237820677505
  24.872643185721834
  25.067927136820586
  25.11573841692058 
  25.458012116630748
  26.01857313404935 

Try to find $4$ smallest (absolute) eigenvalues

In [24]:
# Constructing a set of orthonormal vectors
u2 = zeros(n,4);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;
w = rand(n,1); w = w/norm(u,2);
w = w - (w'*u).*u; w = w - (w'*v).*v;
u2[:,3] = w;
x = rand(n,1); x = x/norm(u,2);
x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
u2[:,4] = x;

# Initialize the eigenvalue
mu = ones(1,4); mu2 = zeros(1,4);

# Define epsilon
eps = 1.0e-10; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = A\u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    w = v2[:,3]; mu[1,3] = norm(w,2); w = w/mu[1,3];
    x = v2[:,4]; mu[1,4] = norm(x,2); x = x/mu[1,4];
    v = v - (v'*u).*u;
    w = w - (w'*u).*u; w = w - (w'*v).*v;
    x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
    u2[:,1] = u; u2[:,2] = v; u2[:,3] = w; u2[:,4] = x;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", 1/mu[1,1])
println("The 2nd eigenvalue is  ", 1/mu[1,2])
println("The 3rd eigenvalue is  ", 1/mu[1,3])
println("The 4th eigenvalue is  ", 1/mu[1,4])
println("# of iterations= ", ii)

The 1st eigenvalue is  0.01296238057116173
The 2nd eigenvalue is  0.03511223314885392
The 3rd eigenvalue is  0.0457727422428922
The 4th eigenvalue is  0.060644435858338626
# of iterations= 49


## Subspace iteration - Test for non-symmetric matrix

In [25]:
B = zeros(3,3);
B[:,:] = Diagonal([1;1;2]); B[1,3]=1;
C = rand(3,3); Q, R = qr(C); B = Q'*B*Q;
println(eigvals(B))
B

[1.0, 2.0, 1.0]


3×3 Array{Float64,2}:
  1.2618    -0.926638  -0.0481386
 -0.217783   1.77084    0.0400447
  0.177497  -0.628246   0.967363 

In [26]:
n=3; m=2;
# Constructing a set of orthonormal vectors
u2 = zeros(n,m);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;

# Initialize the eigenvalue
mu = ones(1,m); mu2 = zeros(1,m);

# Define epsilon
eps = 1.0e-10; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = B*u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    v = v - (v'*u).*u;
    u2[:,1] = u; u2[:,2] = v;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", mu[1,1])
println("The 2nd eigenvalue is  ", mu[1,2])
println("# of iterations= ", ii)

The 1st eigenvalue is  2.0000000000697766
The 2nd eigenvalue is  0.9999999999956017
# of iterations= 36


## QR algorithm

In [27]:
n=3;
Q, R = qr(B);

# Define epsilon
eps = 1.0e-10; ii=0;
mu = ones(n,1); mu2 = zeros(n,1); 

# The loop
while norm(mu2-mu)>eps
    global A2
    mu2 = mu;
    A2 = R*Q;
    Q, R = qr(A2);
    mu = diag(A2);
    ii=ii+1;
end
println("The eigenvaluew are  ", mu)
println("# of iterations= ", ii)

The eigenvaluew are  [2.0, 1.0, 1.0]
# of iterations= 34


In [28]:
A2

3×3 Array{Float64,2}:
  2.0          -0.580223     -0.814458   
 -1.08683e-10   1.0           8.85176e-11
  2.20217e-11  -1.27776e-11   1.0        

## Eigenvalue problem of Laplace operator
$$u_{xx} = \lambda u, \qquad u(0) = u(1) = 0.$$

In [29]:
n = 1000; A = zeros(n-1,n-1);
for ii=1:n-1
    A[ii,ii] = -2;
end
for ii=1:n-2
    A[ii, ii+1]=1;
    A[ii+1, ii]=1;
end
h = 1/n; A = A/h^2;

In [30]:
n = n-1;
# Constructing a set of orthonormal vectors
u2 = zeros(n,4);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;
w = rand(n,1); w = w/norm(u,2);
w = w - (w'*u).*u; w = w - (w'*v).*v;
u2[:,3] = w;
x = rand(n,1); x = x/norm(u,2);
x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
u2[:,4] = x;

# Initialize the eigenvalue
mu = ones(1,4); mu2 = zeros(1,4);

# Define epsilon
eps = 1.0e-13; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = A\u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    w = v2[:,3]; mu[1,3] = norm(w,2); w = w/mu[1,3];
    x = v2[:,4]; mu[1,4] = norm(x,2); x = x/mu[1,4];
    v = v - (v'*u).*u;
    w = w - (w'*u).*u; w = w - (w'*v).*v;
    x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
    u2[:,1] = u; u2[:,2] = v; u2[:,3] = w; u2[:,4] = x;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", 1/mu[1,1])
println("The 2nd eigenvalue is  ", 1/mu[1,2])
println("The 3rd eigenvalue is  ", 1/mu[1,3])
println("The 4th eigenvalue is  ", 1/mu[1,4])
println("# of iterations= ", ii)

The 1st eigenvalue is  9.86959628366954
The 2nd eigenvalue is  39.47828772573999
The 3rd eigenvalue is  88.82578210039104
The 4th eigenvalue is  157.9115923684798
# of iterations= 31
