# Power method

In [1]:
import numpy as np

In [2]:
A = np.array([
    [2.0, 1.0, 5.0],
    [5.0, 7.0, 9.0],
    [4.0, 6.0, 1.0],
])
print('A= ')
print(A)

A= 
[[2. 1. 5.]
 [5. 7. 9.]
 [4. 6. 1.]]


In [3]:
w, v = np.linalg.eig(A)
print('eigenvalues = ', w)

eigenvalues =  [13.78378635  0.83287417 -4.61666053]


## Power method to find the largest (in absolute value) eigenvalue

### Algorithm 0 - test

> $10$ iterations on power method

In [4]:
# initial guess
u = np.random.random((3,1))
# itmax: max. iteration number
itmx = 10
# initial iteration
k=0
while (k<itmx):
  v = A.dot(u)
  lamb = np.linalg.norm(v)
  u = v/lamb
  k = k+1
  print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  1    lamb=  9.638281651910617     error =  4.145504700067823
k=  2    lamb=  14.051322152502014     error =  0.2675358005235733
k=  3    lamb=  13.711001621114265     error =  0.07278473086417492
k=  4    lamb=  13.806354053543185     error =  0.022567701564744524
k=  5    lamb=  13.775856651205354     error =  0.007929700773086523
k=  6    lamb=  13.786389139689726     error =  0.00260278771128597
k=  7    lamb=  13.782907945527434     error =  0.0008784064510063416
k=  8    lamb=  13.784079773898002     error =  0.00029342191956160946
k=  9    lamb=  13.783687984242809     error =  9.83677356316548e-05
k=  10    lamb=  13.783819288363574     error =  3.2936385133908175e-05


### Algorithm 1

$$
\lambda^{(k+1)} = \|\hat{x}^{(k+1)}\| \to |\lambda_1|
$$

In [5]:
# initial guess
u = np.random.random((3,1))
u = u/np.linalg.norm(u)
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
lamb0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = A.dot(u)
  lamb1 = np.linalg.norm(v)
  u = v/lamb1
  rel_diff = abs((lamb1-lamb0)/lamb0)
  k = k+1
  lamb0 = lamb1

print('k= ', k, '   lamb= ', lamb1, '    error = ', abs(lamb1-w[0]))

k=  21    lamb=  13.783786352234568     error =  2.561275636026039e-10


### Algorithm 2

$$
\lambda^{(k+1)} = \ell(\hat{x}^{(k+1)}) \to \lambda_1
$$

In [6]:
# initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
lamb0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = A.dot(u)
  lamb1 = v[1,0]
  u = v/lamb1
  rel_diff = abs((lamb1-lamb0)/lamb0)
  k = k+1
  lamb0 = lamb1

print('k= ', k, '   lamb= ', lamb1, '    error = ', abs(lamb1-w[0]))

k=  21    lamb=  13.783786352233516     error =  2.5507596035367897e-10


## Inverse power method to find the smallest (in absolute value) eigenvalue

### Algorithm 2

$$
\mu^{(k+1)} = \ell(\hat{x}^{(k+1)}) \to \frac{1}{\lambda_1}
$$

In [7]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = np.linalg.solve(A, u)
  mu1 = v[1,0]
  u = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1

# eigenvalue = 1/mu
lamb = 1.0/mu1
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[1]))

k=  16    lamb=  0.8328741741046263     error =  2.617239758251344e-12


## Shift-inverse power method to find the eigenvalue that is closest to a given one

### Algorithm 2

$$
\mu^{(k+1)} = \ell(\hat{x}^{(k+1)}) \to \frac{1}{\lambda_1-\sigma}
$$

In [8]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
# As: shifted matrix
# As = A - sigma*I
As = A - sigma*np.identity(3)
while ( (k<itmx) and (rel_diff>Tol) ):
  v = np.linalg.solve(As, u)
  mu1 = v[1,0]
  u = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1

# eigenvalue = sigma+1/mu
lamb = sigma+1.0/mu1
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  28    lamb=  13.783786352045096     error =  6.6656014041655e-11


## Inverse power method with variant shift to find one of the eigenvalue

### Algorithm 2

$$
\sigma^{(k+1)} = \sigma^{(k)} + \frac{1}{\ell(\hat{x}^{(k+1)})} \to \lambda
$$

In [9]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  sigma0 = sigma
  # As: shifted matrix
  # As = A - sigma*I
  As = A - sigma*np.identity(3)
  v = np.linalg.solve(As, u)
  mu1 = v[1,0]
  u = v/mu1
  sigma = sigma + 1.0/mu1
  rel_diff = abs((sigma0-sigma)/sigma0)
  k = k+1

# eigenvalue = sigma
lamb = sigma
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  5    lamb=  13.783786351978447     error =  7.105427357601002e-15


### Algorithm 3: With Rayleigh quotient

$$
\sigma^{(k+1)} =(x^{(k+1)})^TAx^{(k+1)} \to \lambda
$$

In [10]:
# Initial guess
u = np.random.random((3,1))
u = u/np.linalg.norm(u)
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  sigma0 = sigma
  # As: shifted matrix
  # As = A - sigma*I
  As = A - sigma*np.identity(3)
  v = np.linalg.solve(As, u)
  mu1 = np.linalg.norm(v)
  u = v/mu1
  sigma = (u.T).dot(A.dot(u))
  rel_diff = abs((sigma0-sigma)/sigma0)
  k = k+1

# eigenvalue = sigma
lamb = sigma
print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  5    lamb=  [[13.78378635]]     error =  [[1.24344979e-14]]


## For symmetric matrix

### Power iteration with Rayleigh Quotient to find the largest (in magnitude) eigenvalue

In [11]:
Asym = A+A.T

In [12]:
w, v = np.linalg.eig(Asym)
print('eigenvalues = ', w)

eigenvalues =  [28.35235284  1.35840528 -9.71075812]


In [13]:
# initial guess
u = np.random.random((3,1))
u = u/np.linalg.norm(u)
# itmax: max. iteration number
itmx = 10
# initial iteration
k=0
while (k<itmx):
  v = Asym.dot(u)
  lamb = (u.T).dot(v)
  u = v/np.linalg.norm(v)
  k = k+1
  print('k= ', k, '   lamb= ', lamb, '    error = ', abs(lamb-w[0]))

k=  1    lamb=  [[22.92454796]]     error =  [[5.42780488]]
k=  2    lamb=  [[27.73923998]]     error =  [[0.61311286]]
k=  3    lamb=  [[28.27968394]]     error =  [[0.0726689]]
k=  4    lamb=  [[28.34381448]]     error =  [[0.00853837]]
k=  5    lamb=  [[28.35135103]]     error =  [[0.00100182]]
k=  6    lamb=  [[28.35223532]]     error =  [[0.00011752]]
k=  7    lamb=  [[28.35233906]]     error =  [[1.37865489e-05]]
k=  8    lamb=  [[28.35235123]]     error =  [[1.61727461e-06]]
k=  9    lamb=  [[28.35235265]]     error =  [[1.89719454e-07]]
k=  10    lamb=  [[28.35235282]]     error =  [[2.22556373e-08]]
