# Power method

In [ ]:
import numpy as np

In [37]:
A = np.array([
    [2.0, 1.0, 5.0],
    [5.0, 7.0, 9.0],
    [4.0, 6.0, 1.0],
])
print('A= ')
print(A)

A= 
[[2. 1. 5.]
 [5. 7. 9.]
 [4. 6. 1.]]


In [38]:
w, v = np.linalg.eig(A)
print('eigenvalues = ', w)

eigenvalues =  [13.78378635  0.83287417 -4.61666053]


## Power method to find the largest (in absolute value) eigenvalue

### Algorithm 1 - test

In [ ]:
# initial guess
u = np.random.random((3,1))
# itmax: max. iteration number
itmx = 10
# initial iteration
k=0
while (k<itmx):
  v = A.dot(u)
  mu1 = np.linalg.norm(v)
  v = v/mu1
  k = k+1
  print('k= ', k, '   mu= ', mu1, '    error = ', abs(mu1-w[0]))
  u = v

k=  1    mu=  8.947975119299231     error =  4.835811232679209
k=  2    mu=  13.011076951387173     error =  0.7727094005912676
k=  3    mu=  13.879620395189148     error =  0.09583404321070788
k=  4    mu=  13.730979667636797     error =  0.05280668434164326
k=  5    mu=  13.799113042780178     error =  0.015326690801737541
k=  6    mu=  13.778381774183833     error =  0.005404577794607235
k=  7    mu=  13.785565931253908     error =  0.0017795792754675688
k=  8    mu=  13.783186858684587     error =  0.000599493293853115
k=  9    mu=  13.783986754729934     error =  0.00020040275149391107
k=  10    mu=  13.783719186666827     error =  6.71653116128823e-05


### Algorithm 1

In [ ]:
# initial guess
u = np.random.random((3,1))
u = u/np.linalg.norm(u)
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = A.dot(u)
  mu1 = np.linalg.norm(v)
  v = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1
  u = v

print('k= ', k, '   mu= ', mu1, '    error = ', abs(mu1-w[0]))

k=  21    mu=  13.783786352302874     error =  3.2443381314806174e-10


### Algorithm 2

In [ ]:
# initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = A.dot(u)
  mu1 = v[1,0]
  v = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1
  u = v

print('k= ', k, '   mu= ', mu1, '    error = ', abs(mu1-w[0]))

k=  22    mu=  13.78378635184313     error =  1.3531042952763528e-10


## Inverse power method to find the smallest (in absolute value) eigenvalue

### Algorithm 2

In [ ]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  v = np.linalg.solve(A, u)
  mu1 = v[1,0]
  v = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1
  u = v

# eigenvalue = 1/mu
lamb = 1.0/mu1
print('k= ', k, '   mu= ', lamb, '    error = ', abs(lamb-w[1]))

k=  15    mu=  0.8328741741005522     error =  6.6913141694158185e-12


## Shift-inverse power method to find the eigenvalue that is closest to a given one

### Algorithm 1

In [41]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
# As: shifted matrix
# As = A - sigma*I
As = A - sigma*np.identity(3)
while ( (k<itmx) and (rel_diff>Tol) ):
  v = np.linalg.solve(As, u)
  mu1 = v[1,0]
  v = v/mu1
  rel_diff = abs((mu1-mu0)/mu0)
  k = k+1
  mu0 = mu1
  u = v

# eigenvalue = sigma+1/mu
lamb = sigma+1.0/mu1
print('k= ', k, '   mu= ', lamb, '    error = ', abs(lamb-w[0]))

k=  28    mu=  13.783786352036932     error =  5.849187800777145e-11


## Shift-inverse power method with adaptive shift to find one of the eigenvalue

In [39]:
# Initial guess
u = np.random.random((3,1))
u = u/u[1,0]
# shift
sigma = 10.0
# itmax: max. iteration number
itmx = 100
# initial iteration
k=0
# initial guess of largest eigenvalue
mu0 = 1.0
# tolerance
Tol = 1e-10
# initial relative difference
rel_diff = 1.0
while ( (k<itmx) and (rel_diff>Tol) ):
  sigma0 = sigma
  # As: shifted matrix
  # As = A - sigma*I
  As = A - sigma*np.identity(3)
  v = np.linalg.solve(As, u)
  mu1 = v[1,0]
  v = v/mu1
  sigma = sigma + 1.0/mu1
  rel_diff = abs((sigma0-sigma)/sigma0)
  k = k+1
  u = v
  print('k= ', k, '   sigma= ', sigma)

# eigenvalue = sigma+1/mu
lamb = sigma+1.0/mu1
print('k= ', k, '   mu= ', lamb)

k=  1    sigma=  12.4403857231401
k=  2    sigma=  13.93058392922084
k=  3    sigma=  13.785237096572004
k=  4    sigma=  13.783786500242483
k=  5    sigma=  13.783786351978451
k=  6    sigma=  13.78378635197845
k=  6    mu=  13.783786351978447
