## Power method

As a first example, given a 3-by-3 matrix A

In [1]:
A = [2 1 5; 5 7 9; 4 6 1]

3×3 Array{Int64,2}:
 2  1  5
 5  7  9
 4  6  1

All of it's eigenvalues can be evaluated by the comment "eigvals"

In [2]:
using LinearAlgebra
e_A = eigvals(A); 
println(e_A[1]) 
println(e_A[2]) 
println(e_A[3])

13.78378635197844
0.8328741741072435
-4.616660526085692


# Basic Power method
1. Start with a vector $u:=u^{(0)}$
2. for i=1,2,...,k  Compute (1) $v^{(i)}=Au^{(i-1)}$ (2)$\mu^{(i)}=\|v^{(i)}\|_2$ or $\mu^{(i)}=v^{(i)}_2$  (3) $u^{(i)}=v^{(i)}/\mu^{(i)}$
3. $\mu^{(k)}$ is the largest eigenvalue, and $u^{(k)}$ is the corresponding eigenvector

Given a random vector u, we compute A*u several times, here, 10 times.

In [3]:
# Start with a random vector u
u = rand(3);

# The loop.
for ii=1:10
    v = A*u;
    global mu = norm(v,2);
    u = v/mu;
end
println("After 10 iterations, \n")
println("the largest eigenvalue is approximately ", mu)

After 10 iterations, 

the largest eigenvalue is approximately 13.783738490583946


The second attempt, we define an epsilon to test if the process converges or not.

Given $\varepsilon$, if $|\mu_i-\mu_{i-1}|<\varepsilon$, stop the loop.

In [4]:
# Start with a random vector u
u = rand(3);
mu0 = 0;
mu = 1;

# Define epsilon
eps = 1.0e-10;
ii=0;

# The loop
while abs.(mu-mu0)>eps
    mu0 = mu;
    v = A*u;
    
    # Take the second component of v
    mu = v[2];
    
    u = v/mu;
    ii=ii+1;
end
println("Largest eigenvalue is ", mu)
println("# of iterations= ", ii)

Largest eigenvalue is 13.783786351969674
# of iterations= 24


## Inverse power method
1. Start with a vector $u:=u^{(0)}$ with $\|u\|_2 = 1$
2. for i=1,2,...,k  Compute (1) $v^{(i)}=A^{-1}u^{(i-1)}$ (2)$\mu^{(i)}=v^{(i)}_2$  (3) $u^{(i)}=v^{(i)}/\mu^{(i)}$
3. $\mu^{(k)}$ is the smallest eigenvalue, and $u^{(k)}$ is the corresponding eigenvector

To find the smallest eigenvalue we compute $A^{-1}u$ several times until the process converges.

In [5]:
# Start with a normalized vector
u = rand(3); u=u/norm(u,2);

mu0 = 0;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(mu-mu0)>eps
    mu0 = mu;
    
    # Compute A^{-1}u by A\u
    v = A\u;
    
    mu = v[2];
    u = v/mu;
    ii=ii+1;
end
println("Smallest eigenvalue is ", 1/mu)
println("# of iterations= ", ii)

Smallest eigenvalue is 0.8328741741038486
# of iterations= 16


## Shift-inverse power method
Given $\sigma$
1. Start with a vector $u:=u^{(0)}$ with $\|u\|_2 = 1$
2. for i=1,2,...,k  Compute (1) $v^{(i)}=(A-\sigma I)^{-1}u^{(i-1)}$ (2)$\mu^{(i)}=\|v^{(i)}\|_2$ or $\mu^{(i)}=v^{(i)}_2$  (3) $u^{(i)}=v^{(i)}/\mu^{(i)}$
3. $\mu^{(k)}$ is the eigenvalue closest to $\sigma$, and $u^{(k)}$ is the corresponding eigenvector

To find the eigenvalue that is closest to $\sigma$ we compute $(A-\sigma I)^{-1}u$ several times until the process converges.

In [6]:
u = rand(3); u=u/norm(u,2);
sigma = -10;
mu0 = 0;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(mu-mu0)>eps
    mu0 = mu;
    v = (A-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    ii = ii+1;
end
println("The eigenvalue that is closest to ", sigma, " is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue that is closest to -10 is -4.616660523697937
# of iterations= 30


## Shift-inverse power method - Algorithm 2
Given $\sigma$
1. Start with a vector $u:=u^{(0)}$ with $\|u\|_2 = 1$. $\sigma := \sigma^{(0)}$
2. for i=1,2,...,k  Compute (1) $v^{(i)}=(A-\sigma^{(i-1)} I)^{-1}u^{(i-1)}$ (2)$\mu^{(i)}=v^{(i)}_2$  (3) $u^{(i)}=v^{(i)}/\mu^{(i)}$  (4) $\sigma^{(i)} = \sigma^{(i-1)}+ 1/\mu^{(i)}$
3. $\mu^{(k)}$ is the eigenvalue closest to $\sigma$, and $u^{(k)}$ is the corresponding eigenvector

We take variant shifts $\sigma^{(i)} = \sigma^{(i-1)}+ 1/\mu^{(i)}$ to get a faster convergence.

In [7]:
u = rand(3); u=u/norm(u,2);
sigma = 0;
sigma0 = 1;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (A-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    sigma = sigma+ 1/mu;
    ii = ii+1;
end
println("The eigenvalue is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue is 13.783786351978446
# of iterations= 7


## Shift-inverse power method - Algorithm 3
Given $\sigma$
1. Start with a vector $u:=u^{(0)}$ with $\|u\|_2 = 1$. $\sigma := \sigma^{(0)}$
2. for i=1,2,...,k  Compute (1) $v^{(i)}=(A-\sigma^{(i-1)} I)^{-1}u^{(i-1)}$ (2)$\mu^{(i)}=\|v^{(i)}\|_2$  (3) $u^{(i)}=v^{(i)}/\mu^{(i)}$  (4) $\sigma^{(i)} = (v^{(i)})^{\top}Av^{(i)}$
3. $\mu^{(k)}$ is the eigenvalue closest to $\sigma$, and $u^{(k)}$ is the corresponding eigenvector

Here we take variant shifts $\sigma^{(i)} = (v^{(i)})^{\top}Av^{(i)}$

In [8]:
u = rand(3); u=u/norm(u,2);
sigma = u'*A*u;
sigma0 = 1;
mu = 1;
eps = 1.0e-10;
ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (A-sigma*UniformScaling(1))\u;
    v = v/norm(v,2);
    sigma = v'*A*v;
    ii = ii+1;
end
println("The eigenvalue is ", sigma)
println("# of iterations= ", ii)

The eigenvalue is 0.9680194857371368
# of iterations= 371


Let's try a bigger symmetric matrix $B$, with size $n=10$. We'll compute the eigenvalue closet to -1 ($\sigma:=-1$) with all 3 algorithms.

In [9]:
n = 10;
# Construct a symmectic matrix B
B = rand(n,n) .- 0.5; B = B+B';

e_B = eigvals(B);
for ii=1:n
    println(e_B[ii]) 
end

-2.5202110301277574
-1.403719923670342
-1.0143557767212243
-0.6702647055502657
-0.2627246193187113
0.17939266198089765
0.30484927327071903
1.0656139184962172
1.5071434258996255
1.6830250192285676


Shift-inverse power method - Algorithm 1

In [10]:
u = rand(n); u=u/norm(u,2);
sigma = -1;
mu0 = 0; mu = 1;
eps = 1.0e-10; ii=0;
while abs.(mu-mu0)>eps
    mu0 = mu;
    v = (B-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    ii = ii+1;
end
println("The eigenvalue is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue is -1.014355776721224
# of iterations= 11


Shift-inverse power method - Algorithm 2

In [11]:
u = rand(n); u=u/norm(u,2);
sigma = -1; sigma0 = 1;
mu = 1;
eps = 1.0e-10; ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (B-sigma*UniformScaling(1))\u;
    mu = v[2];
    u = v/mu;
    sigma = sigma + 1/mu;
    ii = ii+1;
end
println("The eigenvalue is ", sigma + 1/mu)
println("# of iterations= ", ii)

The eigenvalue is -1.0143557767226348
# of iterations= 7


Shift-inverse power method - Algorithm 3

In [12]:
u = rand(n); u=u/norm(u,2);
sigma = -1; sigma0 = 1;
mu = 1;
eps = 1.0e-10; ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    global v = (B-sigma*UniformScaling(1))\u;
    v = v/norm(v,2);
    sigma = v'*B*v;
    ii = ii+1;
end
println("The eigenvalue is ", sigma)
println("# of iterations= ", ii)

The eigenvalue is -1.0143557767212246
# of iterations= 4


Do you see the difference of numbers of iterations?

In [13]:
lambda_1 = sigma;
v1 = v;

## Deflation (For symmetric matrix)
Given a symmetric metrix $B$, suppose we found the eigenvalue $\lambda_1$ and eigenvector $v_1$,
we can define a new matrix $B_2 = B - \lambda_1 v_1v_1^T$.

Note that $v_1^{\top}v_1=1$

In [14]:
B2 = B - lambda_1*v1*v1';
e_B2 = eigvals(B2); e_B2 = sort(e_B2);
println("Eigenvalues of B","\t","Eigenvalues of B2")
for ii=1:n
    println(e_B[ii], "\t", e_B2[ii])
end

Eigenvalues of B	Eigenvalues of B2
-2.5202110301277574	-2.5202110301277605
-1.403719923670342	-1.4037199236703433
-1.0143557767212243	-0.6702647055502654
-0.6702647055502657	-0.2627246193187119
-0.2627246193187113	2.9633845653316814e-17
0.17939266198089765	0.17939266198089773
0.30484927327071903	0.30484927327071903
1.0656139184962172	1.0656139184962168
1.5071434258996255	1.5071434258996268
1.6830250192285676	1.6830250192285707


We want to choose $x$ such that $x^{\top}v_1=1$. Define $x^{\top} = (1/v_1[1],0,0,...,0)$, $B_3 = B-\lambda_1v_1x^{\top}$.

In [15]:
x = zeros(n); 
x[1] = 1/v1[1];
B3 = B - lambda_1*v1*x';
e_B3 = eigvals(B3); e_B3 = sort(e_B3);
println("Eigenvalues of B","\t","Eigenvalues of B3")
for ii=1:n
    println(e_B[ii], "\t", e_B3[ii])
end

Eigenvalues of B	Eigenvalues of B3
-2.5202110301277574	-2.520211030128337
-1.403719923670342	-1.4037199236732558
-1.0143557767212243	-0.6702647055504336
-0.6702647055502657	-0.26272461930593005
-0.2627246193187113	-1.315157160414284e-11
0.17939266198089765	0.17939266197531967
0.30484927327071903	0.3048492732781795
1.0656139184962172	1.0656139184955158
1.5071434258996255	1.507143425903716
1.6830250192285676	1.6830250192273224


Wielandt Deflation. Define $x=B[1,:]/(\lambda_1 v_1[1])$, $B_4 = B-\lambda v_1 x^{\top}$

In [16]:
x = B[1,:]/(lambda_1*v1[1]);
B4 = B - lambda_1*v1*x';
e_B4 = eigvals(B4); e_B4 = sort(e_B4);
println("Eigenvalues of B","\t","Eigenvalues of B4")
for ii=1:n
    println(e_B[ii], "\t", e_B4[ii])
end

Eigenvalues of B	Eigenvalues of B4
-2.5202110301277574	-2.5202110301291785
-1.403719923670342	-1.40371992367438
-1.0143557767212243	-0.6702647055503771
-0.6702647055502657	-0.2627246193154017
-0.2627246193187113	3.9433475065709685e-16
0.17939266198089765	0.17939266198188464
0.30484927327071903	0.30484927326847766
1.0656139184962172	1.065613918496956
1.5071434258996255	1.50714342589355
1.6830250192285676	1.6830250192306384


Wielandt Deflation

A small test showing that the size of the matrix can be reduced by one

Start with $4\times4$ symmetric matrix $C$, define $x=C[1,:]/(\lambda_1 v_1[1])$, $C_2=C - \lambda_1 v_1 x^{\top}$ and $C_3=C_2[2:4,2:4]$.

In [17]:
n = 4;
C = rand(n,n) .- 0.5; C = C+C';
e_C = eigvals(C);

u = rand(n); u=u/norm(u,2);
sigma = 0; sigma0 = 1;
mu = 1;
eps = 1.0e-10; ii=0;
while abs.(sigma-sigma0)>eps
    sigma0 = sigma;
    v = (C-sigma*UniformScaling(1))\u;
    v = v/norm(v,2);
    sigma = v'*C*v;
    ii = ii+1;
end
lambda_1 = sigma; v1 = v;

x = C[1,:]/(lambda_1*v1[1]);
C2 = C - lambda_1*v1*x';
e_C2 = eigvals(C2); e_C2 = sort(e_C2);

C3 = C2[2:n, 2:n];
e_C3 = eigvals(C3); e_C3 = sort(e_C3);
println("Eigenvalues of C:", "\t", e_C)
println("Eigenvalues of C2:", "\t", e_C2)
println("Eigenvalues of C3:", "\t", e_C3)

Eigenvalues of C:	[-1.27753, -0.429024, -0.307532, 0.993219]
Eigenvalues of C2:	[-1.27753, -0.307532, 2.22045e-16, 0.993219]
Eigenvalues of C3:	[-1.27753, -0.307532, 0.993219]


## Subspace iteration
1. Construct a matrix $Q_0\in \mathbb{R}^{n\times p}$ of orthonormal column vectors.
2. for $k=1,2,...m$  (1) $Z_k = AQ_{k-1}$ (2) $Q_kR_k = Z_k$ (QR-decomposition)
3. The p largest (absolute) eigenvalues are $\|Q_m(:,1)\|_2,\cdots,\|Q_m(:,p)\|_2$. (Where $Q_m(:,l)$ is the $l$ column vector of $Q_m$.)

Note that when $p=1$ this is just the power method.

In [18]:
# Construct a symmetric matrix
n=1000;
A = rand(n, n).-0.5;
A = A+A';

Try to find $4$ largest (absolute) eigenvalues

In [19]:
# Constructing a set of orthonormal vectors
u2 = zeros(n,4);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;
w = rand(n,1); w = w/norm(u,2);
w = w - (w'*u).*u; w = w - (w'*v).*v;
u2[:,3] = w;
x = rand(n,1); x = x/norm(u,2);
x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
u2[:,4] = x;

# Initialize the eigenvalue
mu = ones(1,4); mu2 = zeros(1,4);

# Define epsilon
eps = 1.0e-10; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = A*u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    w = v2[:,3]; mu[1,3] = norm(w,2); w = w/mu[1,3];
    x = v2[:,4]; mu[1,4] = norm(x,2); x = x/mu[1,4];
    v = v - (v'*u).*u;
    w = w - (w'*u).*u; w = w - (w'*v).*v;
    x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
    u2[:,1] = u; u2[:,2] = v; u2[:,3] = w; u2[:,4] = x;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", mu[1,1])
println("The 2nd eigenvalue is  ", mu[1,2])
println("The 3rd eigenvalue is  ", mu[1,3])
println("The 4th eigenvalue is  ", mu[1,4])
println("# of iterations= ", ii)

The 1st eigenvalue is  25.62858180852502
The 2nd eigenvalue is  25.607533277830854
The 3rd eigenvalue is  25.529981069201355
The 4th eigenvalue is  25.40467425824393
# of iterations= 7417


In [20]:
eigvals(A)

1000-element Array{Float64,1}:
 -25.607533234863382
 -25.52998106920135 
 -25.362270901105173
 -25.18962738817082 
 -25.15635697559802 
 -24.83529547185557 
 -24.725779300021422
 -24.577900123972373
 -24.475620107517535
 -24.320835013924963
 -24.05449313694945 
 -23.9228554002026  
 -23.82559928533295 
   ⋮                
  23.90156764420104 
  24.036442118732328
  24.166733416416893
  24.349898332767644
  24.448326930612676
  24.72407638965626 
  24.844971261403163
  24.922309758762864
  25.034471759177194
  25.2586492991905  
  25.404674258244587
  25.62858185152801 

Try to find $4$ smallest (absolute) eigenvalues. (By timing $A^{-1}$, similar to the inverse power method)

In [21]:
# Constructing a set of orthonormal vectors
u2 = zeros(n,4);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;
w = rand(n,1); w = w/norm(u,2);
w = w - (w'*u).*u; w = w - (w'*v).*v;
u2[:,3] = w;
x = rand(n,1); x = x/norm(u,2);
x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
u2[:,4] = x;

# Initialize the eigenvalue
mu = ones(1,4); mu2 = zeros(1,4);

# Define epsilon
eps = 1.0e-10; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = A\u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    w = v2[:,3]; mu[1,3] = norm(w,2); w = w/mu[1,3];
    x = v2[:,4]; mu[1,4] = norm(x,2); x = x/mu[1,4];
    v = v - (v'*u).*u;
    w = w - (w'*u).*u; w = w - (w'*v).*v;
    x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
    u2[:,1] = u; u2[:,2] = v; u2[:,3] = w; u2[:,4] = x;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", 1/mu[1,1])
println("The 2nd eigenvalue is  ", 1/mu[1,2])
println("The 3rd eigenvalue is  ", 1/mu[1,3])
println("The 4th eigenvalue is  ", 1/mu[1,4])
println("# of iterations= ", ii)

The 1st eigenvalue is  0.0071452731182238835
The 2nd eigenvalue is  0.02899078131444122
The 3rd eigenvalue is  0.03288354569132178
The 4th eigenvalue is  0.0800797667298756
# of iterations= 286


## Subspace iteration - Test for non-symmetric matrix

In [22]:
B = zeros(3,3);
B[:,:] = Diagonal([1;1;2]); B[1,3]=1;
C = rand(3,3); Q, R = qr(C); B = Q'*B*Q;
println(eigvals(B))
B

[2.0, 1.0, 1.0]


3×3 Array{Float64,2}:
  1.71977     0.170929   -1.14464 
 -0.0700045   0.983376    0.111327
 -0.186665   -0.0443285   1.29685 

In [23]:
n=3; m=2;
# Constructing a set of orthonormal vectors
u2 = zeros(n,m);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;

# Initialize the eigenvalue
mu = ones(1,m); mu2 = zeros(1,m);

# Define epsilon
eps = 1.0e-10; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = B*u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    v = v - (v'*u).*u;
    u2[:,1] = u; u2[:,2] = v;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", mu[1,1])
println("The 2nd eigenvalue is  ", mu[1,2])
println("# of iterations= ", ii)

The 1st eigenvalue is  2.000000000059948
The 2nd eigenvalue is  1.0000000000735452
# of iterations= 35


## QR algorithm
1. $Q_0 R_0 = qr(B)$ (QR-decomposition)
2. for $i=1,2,...,k$  (1) $B_i = R_{i-1}Q_{i-1}$ (2) $Q_i R_i=B_i$ (3) $\mu_i=diag(B_i)$
3. components of $\mu_k$ are the desired eigenvalues

In [24]:
n=3;
Q, R = qr(B);

# Define epsilon
eps = 1.0e-10; ii=0;
mu = ones(n,1); mu2 = zeros(n,1); 

# The loop
while norm(mu2-mu)>eps
    global A2
    mu2 = mu;
    A2 = R*Q;
    Q, R = qr(A2);
    mu = diag(A2);
    ii=ii+1;
end
println("The eigenvalues are  ", mu)
println("# of iterations= ", ii)

The eigenvalues are  [2.0, 1.0, 1.0]
# of iterations= 33


In [25]:
A2

3×3 Array{Float64,2}:
  2.0          0.330564      0.943783   
 -1.17252e-11  1.0          -1.10661e-11
  3.99197e-11  1.31961e-11   1.0        

## Eigenvalue problem of Laplace operator
$$u_{xx} = \lambda u, \qquad u(0) = u(1) = 0.$$

We can solve this numerically by the difference method.

$$u_{xx} \approx \frac{u(x-h)-2u(x)+u(x+h)}{h^2}$$

$$A:=\frac{1}{h^2}\begin{bmatrix}
-2 & 1 & & & 0\\
1  & -2 & 1 \\
  & 1 & -2 & \ddots \\
  & & \ddots & \ddots & 1 \\
  0 & & & 1 &-2
\end{bmatrix}$$

In [26]:
n = 1000; A = zeros(n-1,n-1);
for ii=1:n-1
    A[ii,ii] = -2;
end
for ii=1:n-2
    A[ii, ii+1]=1;
    A[ii+1, ii]=1;
end
h = 1/n; A = A/h^2;

Solve the 4 smallest (absolute) eigenvalues by subspace iteration.

In [27]:
n = n-1;
# Constructing a set of orthonormal vectors
u2 = zeros(n,4);
u = rand(n,1); u = u/norm(u,2); u2[:,1] = u;
v = rand(n,1); v = v/norm(u,2);
v = v - (v'*u).*u; u2[:,2] = v;
w = rand(n,1); w = w/norm(u,2);
w = w - (w'*u).*u; w = w - (w'*v).*v;
u2[:,3] = w;
x = rand(n,1); x = x/norm(u,2);
x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
u2[:,4] = x;

# Initialize the eigenvalue
mu = ones(1,4); mu2 = zeros(1,4);

# Define epsilon
eps = 1.0e-13; ii=0;

# The loop
while norm(mu2-mu)>eps
    mu2[:] = mu[:];
    v2 = A\u2;
    u = v2[:,1]; mu[1,1] = norm(u,2); u = u/mu[1,1];
    v = v2[:,2]; mu[1,2] = norm(v,2); v = v/mu[1,2];
    w = v2[:,3]; mu[1,3] = norm(w,2); w = w/mu[1,3];
    x = v2[:,4]; mu[1,4] = norm(x,2); x = x/mu[1,4];
    v = v - (v'*u).*u;
    w = w - (w'*u).*u; w = w - (w'*v).*v;
    x = x - (x'*u).*u; x = x - (x'*v).*v; x = x - (x'*w).*w;
    u2[:,1] = u; u2[:,2] = v; u2[:,3] = w; u2[:,4] = x;
    ii=ii+1;
end
println("The 1st eigenvalue is  ", 1/mu[1,1])
println("The 2nd eigenvalue is  ", 1/mu[1,2])
println("The 3rd eigenvalue is  ", 1/mu[1,3])
println("The 4th eigenvalue is  ", 1/mu[1,4])
println("# of iterations= ", ii)

The 1st eigenvalue is  9.86959628366954
The 2nd eigenvalue is  39.47828772573999
The 3rd eigenvalue is  88.82578210039097
The 4th eigenvalue is  157.91159236880276
# of iterations= 35
